### ISSUE TITLE
Modal issue when used with Refined Github

### ISSUE THREAD

**Issue by jonchurch** [katranci/github-npm-stats#26]
Hi there! I love this extension, thank you for creating it.

When using this extension with [Refined Github](https://github.com/sindresorhus/refined-github), I have noticed the modal is obscured by some of the UI:

![Screen Shot 2020-04-14 at 4 01 41 PM](https://user-images.githubusercontent.com/12915163/79268738-41deae80-7e69-11ea-82ad-b39f57d88dfd.png).

Adding a `z-index: 1` to the `<details-menu>` element fixes the issue. 

I used the custom CSS option of Refined Github to fix it, but wanted to file an issue here in case someone else runs into this. The custom CSS I used was:

```css
li.npm-stats > details > details-menu {
z-index: 1;
}
```

**Comment by katranci** [comment]
Hey @jonchurch, thanks a lot for your contribution 🥇 I'll release your fix at the weekend 👍

**Comment by jonchurch** [comment]
Thanks! I just pushed a new commit to the PR, I was previously targeting a style which wasn't always applied.

**Comment by katranci** [comment]
Submitted v1.3.3 with your fix 🎉
